name: Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: seripap/gha-find-replace
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,${{ env.RELEASE_VERSION }}"
